# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wumVLXvV_9rnWoWYdPxKjgCnPvYPWVTM
"""

# app.py
# streamlit run app.py

import io
import json
import pandas as pd
import streamlit as st

# あなたのエンジンをimport（ファイル名に合わせて変更）
import spofes_engine as eng

st.set_page_config(page_title="スポフェス自動編成", layout="wide")

st.title("スポフェス自動編成（リーグ分け＋時程表＋CSV出力）")

# ----------------------------
# 入力：JSONアップロード or テンプレ
# ----------------------------
st.sidebar.header("設定")

DEFAULT_CONFIG = {
    "classes": [
        ["1A", 1, "赤"], ["1B", 1, "青"], ["1C", 1, "黄"],
    ],
    "events": {
        "リレー(男子)": {
            "participants": ["1A", "1B", "1C"],
            "gender": "M",
            "min_teams": 3,
            "parallel": 2,
            "tournament_max_teams": 8,
            "consolation_parallel": 1
        }
    },
    "params": {
        "start_time": "09:00",
        "match_min": 5,
        "change_min": 3,
        "lookahead": 20,
        "league_attempts": 30,
        "seed": 42,
        "tournament_start_time": "13:00",
        "enforce_tournament_start": True,
        "min_games": 3
    }
}

uploaded = st.sidebar.file_uploader("設定JSONをアップロード", type=["json"])

if "config" not in st.session_state:
    st.session_state.config = DEFAULT_CONFIG

if uploaded is not None:
    try:
        st.session_state.config = json.load(uploaded)
        st.sidebar.success("JSONを読み込みました")
    except Exception as e:
        st.sidebar.error(f"JSONの読み込みに失敗: {e}")

st.sidebar.subheader("設定JSON（編集可）")
config_text = st.sidebar.text_area(
    "config",
    value=json.dumps(st.session_state.config, ensure_ascii=False, indent=2),
    height=380
)

colA, colB = st.sidebar.columns(2)
with colA:
    if st.button("このJSONを反映"):
        try:
            st.session_state.config = json.loads(config_text)
            st.success("反映しました")
        except Exception as e:
            st.error(f"JSONが不正です: {e}")

with colB:
    st.download_button(
        "テンプレJSONを保存",
        data=json.dumps(DEFAULT_CONFIG, ensure_ascii=False, indent=2).encode("utf-8"),
        file_name="config_template.json",
        mime="application/json"
    )

cfg = st.session_state.config

# ----------------------------
# 入力チェック（軽め）
# ----------------------------
def normalize_config(cfg: dict):
    classes = cfg.get("classes", [])
    events = cfg.get("events", {})
    params = cfg.get("params", {})

    # classes: list[list] -> list[tuple] に
    classes_t = [tuple(x) for x in classes]

    # events participants: list化（setだとJSONに乗らない）
    events_n = {}
    for name, info in events.items():
        ii = dict(info)
        parts = ii.get("participants", [])
        # エンジン側が set を想定していても対応できるよう set に変換
        ii["participants"] = set(parts)
        events_n[name] = ii

    return classes_t, events_n, params

try:
    classes, events, params = normalize_config(cfg)
except Exception as e:
    st.error(f"設定の整形に失敗しました: {e}")
    st.stop()

# ----------------------------
# 実行ボタン
# ----------------------------
st.subheader("実行")

run = st.button("スケジュール生成", type="primary")

if run:
    with st.spinner("生成中..."):
        try:
            final_timetable, info = eng.try_build_parallel_timetable_with_retries_v2(
                events=events,
                classes=classes,
                start_time=params.get("start_time", "09:00"),
                match_min=int(params.get("match_min", 5)),
                change_min=int(params.get("change_min", 3)),
                lookahead=int(params.get("lookahead", 20)),
                league_attempts=int(params.get("league_attempts", 30)),
                seed=int(params.get("seed", 42)),
            )

            if not info.get("success"):
                st.error("生成に失敗しました")
                st.code(info.get("last_error", "unknown error"))
                st.stop()

            st.success("生成成功！")
            st.session_state.final_timetable = final_timetable
            st.session_state.info = info

        except Exception as e:
            st.error(f"例外で停止しました: {e}")
            st.stop()

# ----------------------------
# 結果表示
# ----------------------------
if "final_timetable" in st.session_state and "info" in st.session_state:
    final_timetable = st.session_state.final_timetable
    info = st.session_state.info

    # リーグ分けを復元
    league_seed = info.get("league_seed", params.get("seed", 42))
    all_event_results = [
        eng.make_event_schedule(event_name, event_info, classes, league_seed=league_seed)
        for event_name, event_info in events.items()
    ]

    st.subheader("リーグ分け")

    league_rows = []
    for ev in sorted(all_event_results, key=lambda x: x["event"]):
        ev_name = ev["event"]
        for L in sorted(ev["leagues"].keys()):
            for team in ev["leagues"][L]:
                league_rows.append({"event": ev_name, "league": L, "team": team})

    df_leagues = pd.DataFrame(league_rows)
    st.dataframe(df_leagues, use_container_width=True, hide_index=True)

    st.subheader("時程表")

    tt_rows = []
    for slot_no, slot in enumerate(final_timetable, start=1):
        if not slot:
            continue
        for g in slot:
            a, b = g.get("display_teams", g.get("teams", (None, None)))
            tt_rows.append({
                "slot_no": slot_no,
                "start": g.get("start", ""),
                "end": g.get("end", ""),
                "event": g.get("event", ""),
                "name": g.get("name", ""),
                "team_a": "" if a is None else str(a),
                "team_b": "" if b is None else str(b),
                "referee": g.get("referee", ""),
                "phase": g.get("phase", ""),
                "gender": g.get("gender", "")
            })

    df_tt = pd.DataFrame(tt_rows)
    st.dataframe(df_tt, use_container_width=True, hide_index=True)

    # ----------------------------
    # CSVダウンロード
    # ----------------------------
    st.subheader("CSVダウンロード")

    def to_csv_bytes(df: pd.DataFrame) -> bytes:
        # Excelで文字化けしにくいutf-8-sig
        return df.to_csv(index=False, encoding="utf-8-sig").encode("utf-8-sig")

    col1, col2 = st.columns(2)
    with col1:
        st.download_button(
            "leagues.csv をダウンロード",
            data=to_csv_bytes(df_leagues),
            file_name="leagues.csv",
            mime="text/csv"
        )

    with col2:
        st.download_button(
            "timetable.csv をダウンロード",
            data=to_csv_bytes(df_tt),
            file_name="timetable.csv",
            mime="text/csv"
        )

    st.caption(f"成功情報: {info}")